### ISSUE TITLE
Feature Request: Project Inspection

### ISSUE THREAD

**Issue by walkerselby** [nikolaikopernik/code-complexity-plugin#13]
Add ability to inspect project, so I can find functions that have the highest complexities and focus on refactoring there. 

If this already exists, my apologies.

**Comment by nikolaikopernik** [comment]
No, there is no such functionality yet.
But I like the idea. I will add it.

**Comment by nikolaikopernik** [comment]
There is a progress on this. |
So I've added inspection feature. However, now I'm fighting with `Slow operations are prohibited on EDT.` Looks like IDEA enhances their rules.

**Comment by nikolaikopernik** [comment]
implemented in v1.5.0
