### ISSUE TITLE
Nesting of lambdas is not taken into account

### ISSUE THREAD

**Issue by hrabur** [nikolaikopernik/code-complexity-plugin#17]
As the author of Cognitive Complexity states [here](https://community.sonarsource.com/t/s3776-cognitive-complexity-of-functions-with-lambda-functions/31641) 
> “nested methods and method-like structures such as lambdas” increment the nesting level.

Which is not the fact here. For example code like this is scored with 0% cognitive complexity
```
    // data is of type Map<String, Map<String, SomeType>>
    public boolean hasOnlyUniqueSomeTypeKeys() {
        return Optional.ofNullable(data)
            .map(data -> data.values().stream()
                .allMatch(list -> list.stream()
                    .map(SomeType::getKey)
                    .allMatch(new HashSet<>()::add)))
            .orElse(true);
    }
```

**Comment by nikolaikopernik** [comment]
Ok, indeed this case was overlooked. I will add +1 for every lambda on second level, + 2 on third and so on. For this case, the complexity will be 1 + 2 + 2 = 5

**Comment by nikolaikopernik** [comment]
No, it looks like it works as expected. The full part from the article:
> B2. Nesting level
> The following structures increment the nesting level:
> • if, else if, else, ternary operator
> • switch
> • for, foreach
> • while, do while
> • catch
> • nested methods and method-like structures such as lambdas
> B3. Nesting increments
> The following structures receive a nesting increment commensurate with their nested depth inside B2 structures:
> • if, ternary operator
> • switch
> • for, foreach
> • while, do while
> • catch
So lambda indeed increases the nesting, but in order to get any adjusted complexity score you need one of the operators from B3 section. 

Try to add `if` in the nested lambda and it will get score according to the nesting rather than +1
