### ISSUE TITLE
JetBrains AI Assistent

### ISSUE THREAD

**Issue by davidsoles** [nikolaikopernik/code-complexity-plugin#18]
Hi,
I am using your plugin, and it works really great. But recently, using **JetBrains AI Assistent Chat**, I noticed that the code fragments inside the chat window are displaying the Cognitive Complexity marks.
![image](https://github.com/nikolaikopernik/code-complexity-plugin/assets/984410/0cb2c35e-2d35-4dd7-b63b-ad4899b3f2eb)
Is there a way to avoid this issue?

Thanks in advance.

**Comment by nikolaikopernik** [comment]
Ok, I will have a look.

**Comment by nikolaikopernik** [comment]
Hi David,
Unfortunately, I don't have a change to test it with AI Assistent (it's not allowed in my company and I'm not going to purchaise IDEA Ultimate myself only to test it).
My suggestion would be to generate a debug version so you can install it locally and play with AI chat and then send me back IDEA log. This way I can try to exclude hints from AI components.

**Comment by davidsoles** [comment]
Hi Nikolai,
You don't have to worry about the license for IntelliJ IDEA. The same effect can be reproduced by using "Find in Files" which has a preview window of the selected file.

**Comment by nikolaikopernik** [comment]
I see.
I added some changes which should hide the complexity hints everywhere except the MAIN editor. 
Please check AI chat component in version 1.5.2 (will be available in a couple of days) and if it's fixed as well I will close this issue.

**Comment by davidsoles** [comment]
Now it is displayed only in the main window. Thanks 👍🏼
