### ISSUE TITLE
Support for IntelliJ IDEA K2 Mode

### ISSUE THREAD

**Issue by polisherm** [nikolaikopernik/code-complexity-plugin#20]
### Suggestion
This plugin is fully compatible with the current mainstream K1 (legacy) mode, but does not seem to support K2 mode. Would you add support for K2 mode?
JetBrains is planning to make K2 mode the default for the IDE.

### What is K2 mode?
Please check following web page.
https://blog.jetbrains.com/idea/2024/08/meet-the-renovated-kotlin-support-k2-mode/

### How Migrating from K2?
Here is the migration guide. I hope it will be helpful.
https://kotlin.github.io/analysis-api/migrating-from-k1.html

**Comment by nikolaikopernik** [comment]
Nice, thanks for submitting the request. I'll take a look

**Comment by nikolaikopernik** [comment]
Fixed in v1.6.0.
Will be available in a day or two after verification by JetBrains

**Comment by polisherm** [comment]
Genius. I was eagerly awaiting this support. Thank you very much.
