### ISSUE TITLE
Text is low contrast when using high contrast mode

### ISSUE THREAD

**Issue by prototype99** [nikolaikopernik/code-complexity-plugin#24]
Fairly simple issue to explain. When using high contrast mode the text is tough to read as seen below:
![image](https://github.com/user-attachments/assets/2b5dd960-8c1b-4fe5-be08-63b315838f25)

**Comment by nikolaikopernik** [comment]
Hey @prototype99, 
Indeed, the colour is a bit off. Will fix

**Comment by nikolaikopernik** [comment]
Fixed in v1.6.1
