### ISSUE TITLE
Not compatible with the version of your running IDE (PyCharm 2023.2)

### ISSUE THREAD

**Issue by smartbiz-tcl** [nikolaikopernik/code-complexity-plugin#4]
Good morning --

Just updated pycharm and got the error saying the plugin is not compatible with the update. Wondering if this is on your roadmap and if so, what needs to be done? I might be able to pitch in.

**Comment by nikolaikopernik** [comment]
Fixed in v1.1.0
Will take a few days for JetBrains to approve the new version.

**Comment by smartbiz-tcl** [comment]
Super cool. Thank you.
