### ISSUE TITLE
Is there a way to disable the icon in the inline hints?

### ISSUE THREAD

**Issue by hemeroc** [nikolaikopernik/code-complexity-plugin#9]
I would like to disable the icon in the inline hints (as in the screenshots).
But I could not find a setting.

Is there any way to do so?

**Comment by nikolaikopernik** [comment]
Ah, the screenshots were made at the time before I added the icons. So no config for this now.

**Comment by hemeroc** [comment]
@nikolaikopernik I added a PR with this functionality

**Comment by nikolaikopernik** [comment]
Wow, thanks! Will check it out

**Comment by nikolaikopernik** [comment]
Released v1.2.1. Will take a few days for IntelliJ to verify it.
